<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="0" failed="1" skipped="4">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-10-22T15:51:56 IST" name="Command line suite" finished-at="2022-10-22T15:52:06 IST" duration-ms="9372">
    <groups>
    </groups>
    <test started-at="2022-10-22T15:51:56 IST" name="Command line test" finished-at="2022-10-22T15:52:06 IST" duration-ms="9372">
      <class name="com.examarly.HomePageWeb">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.examarly.HomePageWeb@31368b99]" started-at="2022-10-22T15:51:56 IST" name="setUp" finished-at="2022-10-22T15:52:01 IST" duration-ms="5174" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="Landingpage()[pri:0, instance:com.examarly.HomePageWeb@31368b99]" started-at="2022-10-22T15:52:01 IST" name="Landingpage" finished-at="2022-10-22T15:52:05 IST" duration-ms="4068" status="FAIL">
          <exception class="org.openqa.selenium.NoSuchWindowException">
            <message>
              <![CDATA[no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=106.0.5249.119)
Build info: version: '4.3.0', revision: 'a4995e2c09*'
System info: host: 'Kishores-MacBook-Air.local', ip: 'fe80:0:0:0:18ae:31ec:933f:f97f%en0', os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '12.6', java.version: '18.0.2.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [29c34523b9c9079dabba431e7b4c8fa7, findElement {using=xpath, value=//button[@class='ng-binding'][1]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 106.0.5249.119, chrome: {chromedriverVersion: 106.0.5249.61 (511755355844..., userDataDir: /var/folders/w2/tnn1nt2x1x7...}, goog:chromeOptions: {debuggerAddress: localhost:49215}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: MAC, proxy: Proxy(), se:cdp: ws://localhost:49215/devtoo..., se:cdpVersion: 106.0.5249.119, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 29c34523b9c9079dabba431e7b4c8fa7]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchWindowException: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=106.0.5249.119)
Build info: version: '4.3.0', revision: 'a4995e2c09*'
System info: host: 'Kishores-MacBook-Air.local', ip: 'fe80:0:0:0:18ae:31ec:933f:f97f%en0', os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '12.6', java.version: '18.0.2.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [29c34523b9c9079dabba431e7b4c8fa7, findElement {using=xpath, value=//button[@class='ng-binding'][1]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 106.0.5249.119, chrome: {chromedriverVersion: 106.0.5249.61 (511755355844..., userDataDir: /var/folders/w2/tnn1nt2x1x7...}, goog:chromeOptions: {debuggerAddress: localhost:49215}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: MAC, proxy: Proxy(), se:cdp: ws://localhost:49215/devtoo..., se:cdpVersion: 106.0.5249.119, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 29c34523b9c9079dabba431e7b4c8fa7
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:569)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:162)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:60)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:387)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:379)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:70)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:39)
at jdk.proxy2/jdk.proxy2.$Proxy13.click(Unknown Source)
at com.examarly.QA_Pages.LandingPageWeb.DontAllow(LandingPageWeb.java:103)
at com.examarly.HomePageWeb.Landingpage(HomePageWeb.java:49)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.examarly.TestRunner.main(TestRunner.java:14)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchWindowException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Landingpage -->
        <test-method signature="About()[pri:0, instance:com.examarly.HomePageWeb@31368b99]" started-at="2022-10-22T15:52:05 IST" name="About" finished-at="2022-10-22T15:52:05 IST" depends-on-methods="com.examarly.HomePageWeb.Landingpage" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.examarly.HomePageWeb.About() on instance com.examarly.HomePageWeb@31368b99 depends on not successfully finished methods 
[com.examarly.HomePageWeb.Landingpage() on instance com.examarly.HomePageWeb@31368b99]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.examarly.HomePageWeb.About() on instance com.examarly.HomePageWeb@31368b99 depends on not successfully finished methods 
[com.examarly.HomePageWeb.Landingpage() on instance com.examarly.HomePageWeb@31368b99]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:150)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.examarly.TestRunner.main(TestRunner.java:14)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- About -->
        <test-method signature="Contact()[pri:0, instance:com.examarly.HomePageWeb@31368b99]" started-at="2022-10-22T15:52:05 IST" name="Contact" finished-at="2022-10-22T15:52:05 IST" depends-on-methods="com.examarly.HomePageWeb.About" duration-ms="1" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.examarly.HomePageWeb.Contact() on instance com.examarly.HomePageWeb@31368b99 depends on not successfully finished methods 
[com.examarly.HomePageWeb.About() on instance com.examarly.HomePageWeb@31368b99]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.examarly.HomePageWeb.Contact() on instance com.examarly.HomePageWeb@31368b99 depends on not successfully finished methods 
[com.examarly.HomePageWeb.About() on instance com.examarly.HomePageWeb@31368b99]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:150)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.examarly.TestRunner.main(TestRunner.java:14)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Contact -->
        <test-method signature="BLOG()[pri:0, instance:com.examarly.HomePageWeb@31368b99]" started-at="2022-10-22T15:52:05 IST" name="BLOG" finished-at="2022-10-22T15:52:05 IST" depends-on-methods="com.examarly.HomePageWeb.FAQ" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.examarly.HomePageWeb.BLOG() on instance com.examarly.HomePageWeb@31368b99 depends on not successfully finished methods 
[com.examarly.HomePageWeb.FAQ() on instance com.examarly.HomePageWeb@31368b99]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.examarly.HomePageWeb.BLOG() on instance com.examarly.HomePageWeb@31368b99 depends on not successfully finished methods 
[com.examarly.HomePageWeb.FAQ() on instance com.examarly.HomePageWeb@31368b99]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:150)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.examarly.TestRunner.main(TestRunner.java:14)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BLOG -->
        <test-method signature="FAQ()[pri:0, instance:com.examarly.HomePageWeb@31368b99]" started-at="2022-10-22T15:52:05 IST" name="FAQ" finished-at="2022-10-22T15:52:05 IST" depends-on-methods="com.examarly.HomePageWeb.Contact" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.examarly.HomePageWeb.FAQ() on instance com.examarly.HomePageWeb@31368b99 depends on not successfully finished methods 
[com.examarly.HomePageWeb.Contact() on instance com.examarly.HomePageWeb@31368b99]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.examarly.HomePageWeb.FAQ() on instance com.examarly.HomePageWeb@31368b99 depends on not successfully finished methods 
[com.examarly.HomePageWeb.Contact() on instance com.examarly.HomePageWeb@31368b99]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:150)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.examarly.TestRunner.main(TestRunner.java:14)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FAQ -->
        <test-method is-config="true" signature="qiut()[pri:0, instance:com.examarly.HomePageWeb@31368b99]" started-at="2022-10-22T15:52:05 IST" name="qiut" finished-at="2022-10-22T15:52:06 IST" duration-ms="109" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- qiut -->
      </class> <!-- com.examarly.HomePageWeb -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
